### ISSUE TITLE
Type-checked EnvoyResource objects?

### ISSUE THREAD

**Issue by acnodal-tc** [3scale/marin3r#69]
Thank you for Marin3r, it looks like it will be very helpful!

One concern I have is that the EnvoyResource object's "Value" is just a blob of text with no structure or validity checking. What are your thoughts on extending it so that it uses the Envoy schemas to only accept valid Envoy configuration structures? It seems like this should be possible but I'm sure that you have thought about it more than me.

Appreciate any thoughts on this topic.

**Comment by roivaz** [comment]
Hi! The idea around this would be to implement a validating admission webhook that checks the validity of the envoy resource values. This way an error in some of the envoy values would be detected before writting the EnvoyConfig in the kubernetes API.
The current implementation of the EnvoyConfig reconciler already performs this validation and avoids trying to write a wrong envoy struct in the xDS server, but this occurs after the EnvoyConfig has already been written to the k8s api. It would be definitely better to have this validation happen before.

**Comment by acnodal-tc** [comment]
I've built webhooks for other projects, would you like me to look into adding one to marin3r? It looks like marin3r already requires the cert-manager so it should be pretty straightforward. A pointer to the validation code would be very helpful.

**Comment by roivaz** [comment]
That would be awesome if you contributed this! :)

We perform validation by trying to deserialize the json/yaml encoded envoy resource into a protobuf struct, using this package https://github.com/3scale/marin3r/tree/master/pkg/envoy/serializer, which has support for both envoy v2 and v3 apis. As an example you can check how this package is used here to deserialize resources and load them into the xDS server: cache.https://github.com/3scale/marin3r/blob/e006cd21f35e6ca141deb6fe96d2a22b6719eae5/pkg/reconcilers/marin3r/envoyconfigrevision/cache.go#L71-L133

Regarding the webhook, we are already using a mutating webhook to inject envoy container into pods, so you just would need to register the new validating webhook here: https://github.com/3scale/marin3r/blob/e006cd21f35e6ca141deb6fe96d2a22b6719eae5/main.go#L246-L279.
