### ISSUE TITLE
Not an issue, just a thank you

### ISSUE THREAD

**Issue by acnodal-tc** [3scale/marin3r#75]
Thank you for writing Marin3r and making it open source! It's very useful but even more than that I've learned a lot from reading the code. Much appreciated!

**Comment by roivaz** [comment]
Thank you very much @acnodal-tc , you are very kind!
Could I ask you how you are using Marin3r? That would be interesting to know, to see if the usage is similar to what we do ourselves or not. It would also be useful to take into account when adding new features :)

**Comment by acnodal-tc** [comment]
We're planning to use Marin3r in what I think is a "standard" way but with one wrinkle. We anticipate that our application will have a lot of churn of the upstream cluster endpoints, so we've implemented an EDS server based on go-control-plane. Marin3r serves the baseline configuration which points to our EDS server. This is more user-friendly in our use case because it means that Marin3r's EnvoyConfigRevisions are more meaningful. If we didn't do this then endpoint changes would spam the EnvoyConfigRevision list and make it difficult to find important configuration changes, i.e., changes made by people, not endpoint add/delete.

Marin3r is feature-complete for what we're doing. I think our only "ask" would be to make it easier to see the feedback from Envoy when it rejects a configuration. It's there in the EnvoyConfigRevisions but it's awkward to find.
